version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TESSERACT_CMD=/usr/bin/tesseract
    networks:
      - appnet
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
    driver: bridge


